# This project follows the Ribose OSS style guide.
# https://github.com/riboseinc/oss-guides
# All project-specific additions and overrides should be specified in this file.

inherit_from:
  - ".rubocop.tb.yml"
  - ".rubocop.ribose.yml"
AllCops:
  DisplayCopNames: false
  StyleGuideCopsOnly: false
  TargetRubyVersion: 2.3
Rails:
  Enabled: true
