sudo: false
dist: trusty
language: ruby
before_install: gem install bundler -v 1.15.1

services:
  - mongodb

script:
  - bundle exec rspec

rvm:
  - "2.4"
  - "2.3"
  - "ruby-head"

gemfile:
  - gemfiles/Rails-5.1.gemfile

matrix:
  include:
    - rvm: "2.4"
      gemfile: "gemfiles/Rails-head.gemfile"
    - rvm: "2.4"
      gemfile: "gemfiles/Rails-5.0.gemfile"
    - rvm: "2.3"
      gemfile: "gemfiles/Rails-4.2.gemfile"
    - rvm: "2.4"
      gemfile: "gemfiles/Rails-5.1.gemfile"
      env:
        - WITHOUT_ACTIVE_RECORD: "1"
    - rvm: "2.4"
      gemfile: "gemfiles/Rails-5.1.gemfile"
      env:
        - WITHOUT_MONGOID: "1"

  allow_failures:
    - rvm: "ruby-head"
    - gemfile: "gemfiles/Rails-head.gemfile"
