dist: trusty
language: ruby

services:
  - mongodb

before_install:
  - gem install bundler -v 1.17.3

install:
  - bundle _1.17.3_ install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}

script:
  - bundle exec rspec

rvm:
  - "2.7"
  - "2.6"
  - "2.5"
  - "2.4"
  - "2.3"
  - "ruby-head"

gemfile:
  - gemfiles/Rails-5.2.gemfile

matrix:
  include:
    - gemfile: "gemfiles/Rails-head.gemfile"
    - gemfile: "gemfiles/Rails-5.1.gemfile"
    - gemfile: "gemfiles/Rails-5.0.gemfile"
    - gemfile: "gemfiles/Rails-4.2.gemfile"
      rvm: "2.3"
    - gemfile: "gemfiles/Rails-5.2.gemfile"
      env:
        - WITHOUT_ACTIVE_RECORD: "1"
    - gemfile: "gemfiles/Rails-5.2.gemfile"
      env:
        - WITHOUT_MONGOID: "1"

  allow_failures:
    - rvm: "ruby-head"
    - gemfile: "gemfiles/Rails-head.gemfile"
